import React, { useState, useEffect, FC } from "react";
import { Loader, Card, FormField, Heading } from "../components";

interface CardProps {
  data: any;
  title: string;
}

const RenderCards: FC<CardProps> = ({ ...props }) => {
  if (props.data?.length > 0)
    return props.data.map((post: any) => <Card key={post._id} {...post} />);

  return (
    <h2 className="mt-5 font-bold text-[#6449ff] text-xl uppercase">
      {props.title}
    </h2>
  );
};

const Home: FC = () => {
  const [loading, setloading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState("");

  return (
    <section className="max-w-7xl mx-auto">
      <Heading
        title="The Community Showcase"
        subTitle="Browse through a collection of imaginative and visually stunning images generated by DALL-E AI"
      />
      <div className="mt-16">
        <FormField />
      </div>
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-[#666e75] text-xl mb-3">
                Showing results for{" "}
                <span className="text-[#222328]">{searchText}</span>
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards data={[]} title="No search results found" />
              ) : (
                <RenderCards data={[]} title="No posts found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
